name: Automerge PRs

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.labels.*.name contains 'automerge'
    steps:
      - name: Auto-merge PR
        uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
