name: Bump Version & Auto-Release

on:
  push:
    branches:
      - main

concurrency:
  group: auto-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed to push tags

      - name: Sync main branch
        run: |
          git fetch origin main
          git pull --ff-only origin main

      - name: Bump version and push tag
        id: bump
        uses: phips28/gh-action-bump-version@v10.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix: 'v'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.bump.outputs.newTag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
