name: Auto-delete merged branches

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  cleanup:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref != 'main' && github.event.pull_request.head.ref != 'development'
    runs-on: self-hosted
    steps:
      - name: Delete merged branch
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch = context.payload.pull_request.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            await github.rest.git.deleteRef({
              owner,
              repo,
              ref: `heads/${branch}`,
            });
