name: Publish Docker image

on:
  push:
    branches:
      - main
      - development
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
          else
            BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
            VERSION="${BRANCH_NAME}-$(git rev-parse --short HEAD)"
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push with SBOM and Provenance
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            telix5000/telegram-story-bot:${{ steps.vars.outputs.version }}
            telix5000/telegram-story-bot:latest
          provenance: true
          sbom: true
