name: Publish Docker image

on:
  push:
    branches:
      - main
      - development
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version and target tag
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION="${GITHUB_REF#refs/tags/}"
            SECONDARY_TAG="latest"
          else
            BRANCH_NAME="${GITHUB_REF#refs/heads/}"
            VERSION="${BRANCH_NAME}-$(git rev-parse --short HEAD)"
            if [[ "$BRANCH_NAME" == "main" ]]; then
              SECONDARY_TAG="latest"
            elif [[ "$BRANCH_NAME" == "development" ]]; then
              SECONDARY_TAG="dev"
            else
              SECONDARY_TAG=""
            fi
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "secondary_tag=$SECONDARY_TAG" >> $GITHUB_OUTPUT

      - name: Build and push with SBOM and Provenance
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            telix5000/telegram-story-bot:${{ steps.vars.outputs.version }}
            telix5000/telegram-story-bot:${{ steps.vars.outputs.secondary_tag }}
          provenance: true
          sbom: true
