# .github/workflows/docker-publish.yml
name: Publish Docker image

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # Needed for provenance attestation

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push with SBOM and Provenance
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: telix5000/telegram-story-bot:latest
          provenance: true           # Enable provenance attestation
          sbom: true                 # Enable SBOM attestation
